version: '3.9'

services:
  redis:
    image: redis:latest
    command: redis-server --save 60 1 --loglevel warning --requirepass admin
    restart: always
    ports:
      - 6380:6379
    volumes:
      - database:/data


networks:
  app_network:


volumes:
  database:
